name: CI
on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: sh gradlew build
        working-directory: tree-app-android
      - name: Assemble Release Bundle
        run: |
          sh gradlew bundleRelease
        working-directory: tree-app-android
      - name: Sign Release
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: tree-app-android/app/build/outputs/bundle/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
      - name: Upload Android Release to Play Store
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ secrets.SERVICE_ACCOUNT_JSON_PLAIN }}
          packageName: de.lmu.treeapp
          releaseFiles: tree-app-android/app/build/outputs/bundle/release/app-release.aab
          track: internal
          whatsNewDirectory: docs/playstore/whatsnew/
